### ISSUE TITLE
compass: remove compass dependency

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-uikit#142]
Remove compass dependency. 🐜 ❗️

**Comment by jpommerening** [comment]
Also: We should definitely put something in place to build CSS from SCSS. I'll try to go with [grunt-sass](https://github.com/sindresorhus/grunt-sass)…

**Comment by jpommerening** [comment]
I can now say, with some certainty, that nothing inside laxar-uikit requires compass.

To validate that, I removed the `@import` directive referencing compass and the config file. I then built the `theme.css` with [node-sass](https://github.com/sass/node-sass) and [postcss/autoprefixer](https://github.com/postcss/autoprefixer) (see changes in `package.json`).

To make sure that all Partials (SCSS files starting with an underscore) still work, I added another file besides the `theme.scss` where I imported the partials in an order that seemed sensible.

That being said, this is still a breaking change, because users might import `laxar-uikit/modules/bootstrap` and expect it to bring `compass` along. (see [diff](https://github.com/LaxarJS/laxar-uikit/commit/18b8e4ec10f5b7ed65c95de7b6c5d953235e3a19#diff-f56a8643ccac9c981a721a0fc6d655e6L3))

Some users might be fine with importing [`compass-mixins`](https://github.com/Igosuki/compass-mixins) without having to commit to the whole Ruby/Compass toolchain. Others might have to stick with Ruby and Compass and import `compass` themselves.

/cc @x1B

**Comment by jpommerening** [comment]
@alex3683, @x1B, @d-voss: Review pls? Also, is it possible this change impacts something else that I missed?

**Comment by alex3683** [comment]
@jpommerening 
If I get that right, we would completely remove compass and dependencies on our side. So if a user needs compass, then because he wants to use it, not because we deliver something needing it. Right?

Using node-sass myself in another project. I'd vote for it.

**Comment by x1B** [comment]
@jpommerening LGTM, assuming the old @import paths (from the config.rb) are now provided for us by webpack?
Needs a big red-flaggy upgrade information entry tho.

**Comment by jpommerening** [comment]
@alex3683: exactly. This change removes Compass from the dependency chain completely. Actually, the Compass specific features were not needed at all. Because of the way Sass works, earlier versions exposed Compass when the user imported styles from `laxar-uikit`. Now, if a user needs Compass they'll have to import it explicitly and add it to their own dependencies in `bower.json` or `package.json`.

@x1B: The `theme.css` is self-contained. If the user wants to use Sass to bundle their own theme and `@import` stuff from `laxar-uikit`, they'd have to configure the `sass-loader` accordingly (i.e. they need to supply the `includePaths` option. Yes, this needs to be documented.

Alternatively we could use [`~`-Imports](https://github.com/jtangelder/sass-loader#imports) to let webpack resolve modules. That would reduce the amount of required setup, but is really webpack specific and not compatible with standalone Sass.

**Comment by x1B** [comment]
@jpommerening ok, I think both ways to emulate the previous import paths should be fine for us, since they dont need any framework support. :+1:

**Comment by jpommerening** [comment]
Then I'll leave it as it is. I'm not comfortable writing webpack specific imports in the SCSS files.

Since there is currently not much of a README, there also is no documentation to update. I'll open another issue for providing proper documentation (at least how to get started with either pre-built themes or how to use the SCSS files).

**Comment by jpommerening** [comment]
Implemented on `master` (`v2.0.0`)

# BREAKING CHANGE

Laxar-UIKit no longer exports [Compass](http://compass-style.org) specific mixins and functions.

We strongly recommend switching to plain Sass, as Compass is no longer maintained, alternatives (libsass, [node-sass](https://github.com/sass/node-sass)) are faster by [an order of magnitude](http://www.moovweb.com/blog/libsass/), easier to set up and integrate better with JavaScript based build tools such as webpack.

If you need Compass mixins and functions you can use [compass-mixins](https://github.com/Igosuki/compass-mixins) which is compatible with node-sass and available via NPM and Bower. Refer to the Laxar-UIKit [README](https://github.com/LaxarJS/laxar-uikit/blob/master/README.md) for setup instructions.

If you absolutely need to use the original, Ruby-based, Compass, you can still do that. You just need to `@import "compass";` yourself.
