### ISSUE TITLE
Date formatter returns date minus one day

### ISSUE THREAD

**Issue by root42** [LaxarJS/laxar-uikit#156]
The date formatter will return date minus one day when fed a simple ISO Date (e.g. 2007-01-01 returns 31.12.2006 in the below example).

Example:

      var dateFormat = ui.formatter.create( 'date', {
         dateFormat: 'DD.MM.YYYY'
      } );
      $scope.dateFormatter = function ( isoString ) {

         if ( isoString === '' ) {
            var today = new Date();
            var past = new Date( today.getFullYear() - 10, 0, 1 )
            return dateFormat( past.toISOString().split( "T" )[0] );
         } else {
            return dateFormat( isoString );
         }
      };

**Comment by jpommerening** [comment]
Hi @root42!

Looks like the timezone is the culprit here, but I'm not sure this is an issue with `laxar-uikit`.

In your example `past` is set to be exactly new year *at GMT+01*.
Then `past.toISOString()` is called and [(implicitly) converts to UTC](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString), so at that point you get 11pm UTC on new year's eve of the year before.
This still seems to be correct, but what's finally passed to the formatter is `2006-12-31`, after splitting at `T` to drop the time *and timezone* information.

```js
var today = new Date();
// => Tue Jul 25 2017 15:08:42 GMT+0200 (CEST)
var past = today.getFullYear() - 10, 0, 1 );
// => Mon Jan 01 2007 00:00:00 GMT+0100 (CET)
var string = past.toISOString();
// => "2006-12-31T23:00:00.000Z"
var input = string.split( 'T' )[0];
// => "2006-12-31"
```

For future versions, I think we should allow for `Date` objects to be passed in instead of enforcing strings. Moment.js can handle `Date` objects just fine…

In the meantime, can you see what happens, if you call `dateFormat` with the `past` variable without doing any string operations beforehand? If that fails, we really *do* have an issue here.

**Comment by alex3683** [comment]
@jpommerening We can additionally allow Date objects, but should still allow ISO date strings. This is for simpler use with most REST APIs where dates are usually encoded as ISO strings.

**Comment by jpommerening** [comment]
@alex3683 That's what I meant :+1:

**Comment by x1B** [comment]
@jpommerening we should probably open a new _enhancement_ for the Date object stuff and close this. Amirite?

**Comment by jpommerening** [comment]
:+1: agreed

**Comment by jpommerening** [comment]
@root42 I'll close this in favor of #157 as suggested by @x1B
